### ISSUE TITLE
set_zone_setpoint() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by phdelodder** [zxdavb/evohome_cc#13]
unable to set the setpoint of a zone

using version 0.5.16a

```
2021-03-07 13:43:33 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140328212481696] set_zone_setpoint() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 642, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 679, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 544, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 404, in async_set_temperature
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/evohome_cc/climate.py", line 243, in set_temperature
    self._evo_device.setpoint = setpoint
  File "/usr/local/lib/python3.8/site-packages/evohome_rf/zones.py", line 769, in setpoint
    cmd = Command.set_zone_setpoint(self._ctl.id, self.idx, value)
TypeError: set_zone_setpoint() takes 3 positional arguments but 4 were given
```

**Comment by phdelodder** [comment]
Fixed with 0.5.17
