### ISSUE TITLE
KeyError: 'client_state'

### ISSUE THREAD

**Issue by phdelodder** [zxdavb/evohome_cc#28]
Logger: homeassistant.setup
Source: custom_components/evohome_cc/__init__.py:188
First occurred: 7:50:34 (1 occurrences)
Last logged: 7:50:34

Error during setup of component evohome_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/evohome_cc/__init__.py", line 100, in async_setup
    await broker.async_restore_client_state()
  File "/config/custom_components/evohome_cc/__init__.py", line 188, in async_restore_client_state
    await self.client._set_state(**app_storage["client_state"])
KeyError: 'client_state'

**Comment by phdelodder** [comment]
Solved with latest push
