### ISSUE TITLE
AttributeError: 'Evohome' object has no attribute 'devices'

### ISSUE THREAD

**Issue by phdelodder** [zxdavb/evohome_cc#3]
When using evohome_rf 0.5.0, I get the following error at startup: 

```
05': {'heating_type': 'radiator_valve', 'sensor': '04:155445', 'devices': ['04:155445']}, '06': {'heating_type': 'radiator_valve', 'sensor': '04:155407', 'devices': ['04:155407']}, '07': {'heating_type': 'radiator_valve', 'sensor': '04:155403', 'devices': ['04:155403']}, '08': {'heating_type': 'radiator_valve', 'sensor': '04:050559', 'devices': ['04:050559']}, '09': {'heating_type': 'radiator_valve', 'sensor': '04:081849', 'devices': []}}}
2021-01-24 18:06:36 ERROR (MainThread) [custom_components.evohome_cc.evohome_rf] handle_exception(): Caught: Task exception was never retrieved
2021-01-24 18:06:36 ERROR (MainThread) [asyncio] Unhandled error in exception handler
context: {'message': 'Task exception was never retrieved', 'exception': AttributeError("'Evohome' object has no attribute 'devices'"), 'future': <Task finished name='Task-11943' coro=<EvoBroker.update() done, defined at /config/custom_components/evohome_cc/__init__.py:167> exception=AttributeError("'Evohome' object has no attribute 'devices'")>}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1744, in call_exception_handler
    self._exception_handler(self, context)
  File "/config/custom_components/evohome_cc/evohome_rf/__init__.py", line 118, in handle_exception
    raise exc
  File "/config/custom_components/evohome_cc/__init__.py", line 192, in update
    if new_sensors(self):
  File "/config/custom_components/evohome_cc/__init__.py", line 76, in new_sensors
    for d in broker.client.evo.devices
AttributeError: 'Evohome' object has no attribute 'devices'
```

**Comment by zxdavb** [comment]
You are very keen - a new **evohome_cc** is in the works - please be patient, I will post on https://community.home-assistant.io/t/honeywell-ch-dhw-via-rf-hgi80-hgs80-includes-evohome/151584/360 when it is ready to be tested.
